version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  db:
    image: postgres
    container_name: "local_postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
